baseurl = "/"

# Site title
title = "Test Site"

# Copyright
copyright = "(c) 2016 yourname."

# Language
languageCode = "en-EN"

# SES friendly url:s
canonifyurls = true

# Frontmatter format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
 theme = "hugo-bootstrap-mod"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "appernetic"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "yourname"
    email = "yourname@example.com"

#
# All parameters below here are optional and can be mixed and matched.
#

[params.theme]
  name = "paper"

[params]
    # You can use markdown here.
    brand = "foobar"
    topline = "few words about your site"
    footline = "code with <i class='fa fa-heart'></i>"

    # Text for the top menu link, which goes to the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

	# Show a sidebar menu
    showRightSidebar = true
    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "Appernetic" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "111074595662096336201" # Your Google+ profile ID
    facebook = "Appernetic" # Your Facebook profile ID
    twitter = "Appernetic" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
