name = "Hugo Bootstrap mod"
license = "MIT"
licenselink = "https://github.com/appernetic/hugo-bootstrap-mod/LICENSE.md"
description = "A hugo theme using bootstrap, bootswatch, font-awesome, highlight.js"
homepage = "https://github.com/appernetic/hugo-bootstrap-mod"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]
min_version = 0.14

[author]
    name = "Göran Svensson"
    homepage = "http://appernetic.github.io"

[original]
    author =  "Murali Rath/Steven Enten"
    homepage = "https://github.com/enten/hyde-y"
    repo = "https://github.com/enten/hyde-y"
